# Generated by Django 3.1.4 on 2021-01-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210101_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='feedback',
            field=models.TextField(null=True),
        ),
    ]
