# Generated by Django 3.1.4 on 2021-01-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_account_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='feedback',
        ),
    ]
