# Generated by Django 3.1.4 on 2021-01-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210103_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
