---
- hosts: localhost
  tasks:
  - name: Create postgres network
    docker_network:
      name: postgres

  - name: Deploy container
    docker_container:
      name: postgres
      image: postgres:13-alpine
      restart_policy: always
      ports:
        - "5432:5432"
      networks:
        - name: postgres
      volumes:
        - /home/postgres/postgres-data:/var/lib/postgresql/data
      env:
        POSTGRES_DB: "{{ env['POSTGRES_NAME'] }}"
        POSTGRES_USER: "{{ env['POSTGRES_USER'] }}"
        POSTGRES_PASSWORD: "{{ env['POSTGRES_PASSWORD'] }}"
      state: started
  
  - name: Get container info
    docker_container_info:
      name: postgres
    register: result

  - name: Does container exist?
    debug:
      msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"
  
  - name: Print container status
    debug:
      msg: "The container is {{ result.container['State']['Status'] }} (using image '{{ result.container['Config']['Image'] }}')"
    when: result.exists