---
- hosts: "{{ host }}"
  tasks:
  - name: Pull docker image
    docker_image:
      name: tarrott/academy:latest
      source: pull

  - name: Deploy container
    docker_container:
      name: academy
      image: tarrott/academy:latest
      network:
        - name: academy_backend
        - name: postgres
      env:
        DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
        DEBUG: ${DEBUG}
        ALLOWED_HOSTS: ${ALLOWED_HOSTS}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_NAME: ${POSTGRES_NAME}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        DJANGO_SU_NAME: ${DJANGO_SU_NAME}
        DJANGO_SU_EMAIL: ${DJANGO_SU_EMAIL}
        DJANGO_SU_PASSWORD: ${DJANGO_SU_PASSWORD}
      state: present

  - name: Get container info
    docker_container_info:
      name: academy
    register: result

  - name: Does container exist?
    debug:
      msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"
  
  - name: Print container status
    debug:
      msg: "The container is {{ result.container['State']['Status'] }} (using image '{{ result.container['Config']['Image'] }}')"
    when: result.exists