version: '3'
services:
  nginx:
    image: nginx:1.18
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./academy/media:/app/media
      - ./academy/static:/app/static
    networks:
      - backend
    depends_on:
      - academy
  academy:
    build: .
    command: gunicorn academy.wsgi --bind 0.0.0.0:80
    restart: always
    ports:
      - 8081:80
    networks:
    - backend
    volumes:
    - ./academy:/app
    environment:
    - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    - DEBUG=${DEBUG}
    - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    - POSTGRES_HOST=${POSTGRES_HOST}
    - POSTGRES_PORT=${POSTGRES_PORT}
    - POSTGRES_NAME=${POSTGRES_NAME}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - DJANGO_SU_NAME=${DJANGO_SU_NAME}
    - DJANGO_SU_EMAIL=${DJANGO_SU_EMAIL}
    - DJANGO_SU_PASSWORD=${DJANGO_SU_PASSWORD}
    depends_on: 
      - postgres
  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    networks:
    - backend
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=${POSTGRES_USER}"
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  pg-admin:
    image: dpage/pgadmin4:4.29
    restart: always
    ports:
      - 8082:80
    networks:
      - backend
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
networks:
  backend:
    driver: bridge
