# Generated by Django 3.1.4 on 2021-01-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='logo',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='date',
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.CharField(blank=True, help_text='Text shown on homepage under the name and image.', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='capacity',
            field=models.SmallIntegerField(blank=True, help_text='If speicifed, the number will be shown along with the session title on the homepage and account page.', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='full',
            field=models.BooleanField(default=False, help_text='If checked, then then users can no longer register for the session and it will be greyed out on the homepage.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='content',
            field=models.TextField(blank=True, help_text='Text shown on the individual resource page to describe the resource in depth.', null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
