# Generated by Django 3.1.4 on 2021-01-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='resource_default.jpg', upload_to='resource_logos')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'feedback'},
        ),
    ]
